# Generated by Django 2.2 on 2021-06-04 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Skill',
        ),
    ]
