# Generated by Django 2.2 on 2021-06-04 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_delete_skill'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='aboutme',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='duration',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='edate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='sdate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
